# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/inspectit
    steps:
      - checkout:
          path: ~/inspectit/repo
      - persist_to_workspace:
          root: ~/inspectit
          paths:
            - repo

  sys-openjdk8: &base_test_job
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/inspectit
    steps:
      - attach_workspace:
          at: ~/inspectit
      - run: cd repo && ./gradlew assemble
      - run: cd repo && ./gradlew test
      - run: cd repo && ./gradlew systemTest
      - store_test_results:
          path: ~/inspectit/repo/inspectit-ocelot-agent/build/test-results
      - store_test_results:
          path: ~/inspectit/repo/inspectit-ocelot-core/build/test-results

  sys-openjdk9:
    <<: *base_test_job
    docker:
      - image: circleci/openjdk:9-jdk

  sys-openjdk11:
    <<: *base_test_job
    docker:
      - image: circleci/openjdk:11-jdk

  sys-ibmjava8:
    <<: *base_test_job
    docker:
      - image: ibmcom/ibmjava:8-sdk

  sys-oracle8-codecov:
    <<: *base_test_job
    steps:
      - attach_workspace:
          at: ~/inspectit
      - run: sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository -y ppa:webupd8team/java
      - run: sudo apt-get --allow-unauthenticated update
      - run: echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
      - run: sudo apt-get --allow-unauthenticated install -y oracle-java8-installer
      - run: java -version
      - run: cd repo && ./gradlew assemble
      - run: cd repo && ./gradlew test
      - run: cd repo && ./gradlew systemTest
      - store_test_results:
          path: ~/inspectit/repo/inspectit-ocelot-agent/build/test-results
      - store_test_results:
          path: ~/inspectit/repo/inspectit-ocelot-core/build/test-results
      - run: cd repo && ./gradlew codeCoverageReport
      - run: cd repo && bash <(curl -s https://codecov.io/bash)

  sys-oracle11:
    <<: *base_test_job
    steps:
      - attach_workspace:
          at: ~/inspectit
      - run: sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository -y ppa:linuxuprising/java
      - run: sudo apt-get --allow-unauthenticated update
      - run: echo oracle-java11-installer shared/accepted-oracle-license-v1-2 select true | sudo /usr/bin/debconf-set-selections
      - run: sudo apt-get --allow-unauthenticated install -y oracle-java11-installer
      - run: java -version
      - run: cd repo && ./gradlew assemble
      - run: cd repo && ./gradlew test
      - run: cd repo && ./gradlew systemTest
      - store_test_results:
          path: ~/inspectit/repo/inspectit-ocelot-agent/build/test-results
      - store_test_results:
          path: ~/inspectit/repo/inspectit-ocelot-core/build/test-results

  compile-jmh:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/inspectit
    steps:
      - attach_workspace:
          at: ~/inspectit
      - run: cd repo && ./gradlew jmhCompile

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - sys-oracle8-codecov: &requires_checkout
          requires:
            - checkout
#      - sys-oracle11:
#          <<: *requires_checkout
#      - sys-openjdk8:
#          <<: *requires_checkout
#      - sys-openjdk9:
#          <<: *requires_checkout
#      - sys-openjdk11:
#          <<: *requires_checkout
#      - sys-ibmjava8:
#          <<: *requires_checkout
#      - jmh-compile:
#          <<: *requires_checkout
