# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/inspectit
    steps:
      - checkout:
          path: ~/inspectit/repo
      - persist_to_workspace:
          root: ~/inspectit
          paths:
            - repo

  openjdk8-test: &base_test_job
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/inspectit
    steps:
      - attach_workspace:
          at: ~/inspectit
      - run: cd repo && ./gradlew assemble test systemTest

  openjdk9-test:
    <<: *base_test_job
    docker:
      - image: circleci/openjdk:9-jdk

  openjdk11-test:
    <<: *base_test_job
    docker:
      - image: circleci/openjdk:11-jdk

  ibmjava8-test:
    <<: *base_test_job
    docker:
      - image: ibmcom/ibmjava:8-sdk

  oracle8-test:
    <<: *base_test_job
    steps:
      - attach_workspace:
          at: ~/inspectit
      - run: sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository -y ppa:webupd8team/java
      - run: sudo apt-get --allow-unauthenticated update
      - run: echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
      - run: sudo apt-get --allow-unauthenticated install -y oracle-java8-installer
      - run: java -version
      - run: cd repo && ./gradlew assemble test systemTest

  oracle11-test:
    <<: *base_test_job
    steps:
      - attach_workspace:
          at: ~/inspectit
      - run: sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository -y ppa:linuxuprising/java
      - run: sudo apt-get --allow-unauthenticated update
      - run: echo oracle-java11-installer shared/accepted-oracle-license-v1-2 select true | sudo /usr/bin/debconf-set-selections
      - run: sudo apt-get --allow-unauthenticated install -y oracle-java11-installer
      - run: java -version
      - run: cd repo && ./gradlew assemble test systemTest


workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - oracle8-test: &requires_checkout
          requires:
            - checkout
      - oracle11-test:
          <<: *requires_checkout
      - openjdk8-test:
          <<: *requires_checkout
      - openjdk9-test:
          <<: *requires_checkout
      - openjdk11-test:
          <<: *requires_checkout
      - ibmjava8-test:
          <<: *requires_checkout