spring:
  datasource:
    url: jdbc:sqlite:${inspectit-config-server.working-directory}/users.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baselineOnMigrate: true
    baselineVersion: 1

# server properties - see https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server-properties
server:
  port: 8090

inspectit-config-server:
  # the directory which is used as working directory
  working-directory: working_directory
  # the expiration duration of JWT tokens
  token-lifespan: 60m
  # the e-mail suffix used for internal users
  mail-suffix: '@inspectit.rocks'
  # the default admin user
  default-user:
    name: admin
    password: admin
  # size of the internal thread pool
  thread-pool-size: 4
  # the maximum number of active agents connected to this server
  # only used to limit the sizes of internal caches
  max-agents: 10000
  # If an agent didn't fetched its configuration for this duration, it is forgotten and evicted from all caches
  agent-eviction-delay: 1h
  # security settings
  security:
    # Whether LDAP authentication should be used
    # See the documentation on how to configure LDAP correctly: https://inspectit.github.io/inspectit-ocelot/docs/config-server/user-authentication
    ldap-authentication: false
    # If enabled, non-admin users cannot promote their own changes.
    # The writing of the configuration and the promotion needs to be done by two separate persons.
    four-eyes-promotion: false
  # settings for the agent commands
  agent-command:
    # after this time, commands which have not been fetched will be removed
    command-timeout: 2m
    # timeout how long a command will wait for a response from the agent
    response-timeout: 30s
    # the size of each agents' command queue
    command-queue-size: 100
    # the max. time an agent is allowed to wait for a new command
    agent-polling-timeout: 30s

  remote-configurations:
    enabled: true
    remote-name: remote-configuration
    git-repository-uri: git@github.com:mariusoe/config-push.git
    source-branch:
    target-branch: rm-live-2
    authentication-type: PPK
    username: mariusoe
    password: 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
    private-key-file: C:/Users/mo/.ssh/id_rsa

# ACTUATOR PROPERTIES
management:
  # Whether to enable or disable all endpoints by default.
  endpoints.enabled-by-default: false
  endpoint:
    # Whether to enable the health endpoint.
    health.enabled: true
  # HEALTH INDICATORS
  health:
    # Whether to enable LDAP health check.
    ldap.enabled: ${inspectit-config-server.security.ldap-authentication}