spring:
  datasource:
    url: jdbc:sqlite:${inspectit.working-directory}/users.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

server:
  port: 8090

inspectit:
  working-directory: working_directory
  token-lifespan: 60m
  default-user:
    name: admin
    password: admin

  thread-pool-size: 4

  # the maximum number of active agents connected to this server
  # only used to limit the sizes of internal caches
  max-agents: 10000
  # after this time has elpased since an agent fetched his configuration, he ist forgotten and evicted from all caches
  agent-eviction-delay: 1h