server:
  port: 8090
inspectit:
  working-directory: working_directory
  token-lifespan: 60m
  default-user:
    name: admin
    password: admin

  thread-pool-size: 4

  # the maximum number of active agents connected to this server
  # only used to limit the sizes of internal caches
  max-agents: 10000