spring:
  datasource:
    url: jdbc:sqlite:${inspectit.working-directory}/users.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

server:
  port: 8090

inspectit-server-config:
  working-directory: working_directory
  token-lifespan: 60m
  default-user:
    name: admin
    password: admin

  thread-pool-size: 4

  # the maximum number of active agents connected to this server
  # only used to limit the sizes of internal caches
  max-agents: 10000
  # If an agent didn't fetched its configuration for this duration, it is forgotten and evicted from all caches
  agent-eviction-delay: 1h

  security:
    # Whether LDAP authentication should be used
    ldap-authentication: false

# ACTUATOR PROPERTIES
management:
  # Whether to enable or disable all endpoints by default.
  endpoints.enabled-by-default: false
  endpoint:
    # Whether to enable the health endpoint.
    health.enabled: true
  # HEALTH INDICATORS
  health:
    # Whether to enable LDAP health check.
    ldap.enabled: ${inspectit.security.ldap-authentication}