
inspectit:
  instrumentation:

    scopes:
      AutoTracingTest-instrumentMe:
        type:
          name: AutoTracingTest
          matcher-mode: ENDS_WITH
        methods:
          - name: instrumentMe

    rules:
      AutoTracingTest-instrumentMe:
        scopes:
          AutoTracingTest-instrumentMe: true
        tracing:
          start-span: true
          auto-trace: true