inspectit:
  instrumentation:
    actions:

      get_arg0:
        input:
          _arg0: Object
        value: _arg0

      get_arg1:
        input:
          _arg1: Object
        value: _arg1

      get_arg2:
        input:
          _arg2: Object
        value: _arg2

      get_return_value:
        input:
          _returnValue: Object
        value: _returnValue

      get_method_name:
        input:
          _methodName: String
        value: _methodName

