inspectit:

  instrumentation:

    scopes:
      TraceSettingsTest-root:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: root
            matcher-mode: STARTS_WITH
      TraceSettingsTest-nested:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: nested
            matcher-mode: STARTS_WITH

      TraceSettingsTest-attributesSetterWithoutSpan:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: attributesSetterWithoutSpan
      TraceSettingsTest-attributesSetterWithoutSpanWithConditions:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: attributesSetterWithoutSpanWithConditions

      TraceSettingsTest-conditionalRoot:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: conditionalRoot

      TraceSettingsTest-named:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: named
            matcher-mode: STARTS_WITH

      TraceSettingsTest-asyncInterleaved:
        type:
          name: TraceSettingsTest$AsyncTask
          matcher-mode: ENDS_WITH
        methods:
          - name: doAsync

      TraceSettingsTest-samplingTestEndMarker:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: samplingTestEndMarker


      TraceSettingsTest-fixedSamplingRateTest:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: fixedSamplingRateTest

      TraceSettingsTest-dynamicSamplingRateTest:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: dynamicSamplingRateTest

    rules:
      TraceSettingsTest-startspan:
        scopes:
          TraceSettingsTest-root: true
          TraceSettingsTest-nested: true
        tracing:
          start-span: true

      TraceSettingsTest-attributesSetterWithoutSpan:
        scopes:
          TraceSettingsTest-attributesSetterWithoutSpan: true
        tracing:
          attributes:
            entry: entry_val
            exit: exit_val
        entry:
          entry_val:
            action: set
            constant-input: {value: "const"}
        exit:
          exit_val:
            action: get_return_value


      TraceSettingsTest-attributesSetterWithoutSpanWithConditions:
        scopes:
          TraceSettingsTest-attributesSetterWithoutSpanWithConditions: true
        tracing:
          attributes:
            entry: entry_val
            exit: exit_val
          attribute-conditions:
            only-if-true: should_capture_attribs
        entry:
          should_capture_attribs:
            action: get_arg0
          entry_val:
            action: set
            constant-input: {value: "const"}
        exit:
          exit_val:
            action: get_return_value

      TraceSettingsTest-conditionalRoot:
        scopes:
          TraceSettingsTest-conditionalRoot: true
        tracing:
          start-span: true
          start-span-conditions:
            only-if-true: should_capture
        entry:
          should_capture:
            action: get_arg0

      TraceSettingsTest-named:
        scopes:
          TraceSettingsTest-named: true
        tracing:
          start-span: true
          name: name_val
        entry:
          name_val:
            action: get_arg0

      TraceSettingsTest-asyncInterleaved:
        scopes:
          TraceSettingsTest-asyncInterleaved: true
        tracing:
          start-span: true
          continue-span: span_id
          end-span: true
          end-span-conditions: {only-if-true: end_span_arg}
          store-span: span_id
          attributes:
            "1": att_1
            "2": att_2
            "3": att_3

        entry:
          span_id:
            action: read_attachment_on_this
            constant-input: {key: "span_obj"}
        exit:
          do_write_span_obj:
            action: replace_attachment_on_this
            constant-input: {key: "span_obj"}
            data-input: {value: span_id}
          att_1: { action: get_arg0 }
          att_2: { action: get_arg1 }
          att_3: { action: get_arg2 }
          end_span_arg: { action: get_arg3 }


      TraceSettingsTest-samplingTestEndMarker:
        scopes:
          TraceSettingsTest-samplingTestEndMarker: true
        tracing:
          start-span: true
          name: name_val
        entry:
          name_val:
            action: get_arg0


      TraceSettingsTest-fixedSamplingRateTest:
        scopes:
          TraceSettingsTest-fixedSamplingRateTest: true
        tracing:
          start-span: true
          name: name_val
          sample-probability: 0.5
        entry:
          name_val:
            action: get_arg0


      TraceSettingsTest-dynamicSamplingRateTest:
        scopes:
          TraceSettingsTest-dynamicSamplingRateTest: true
        tracing:
          start-span: true
          name: name_val
          sample-probability: sample_prob
        entry:
          name_val:
            action: get_arg0
          sample_prob:
            action: get_arg1