inspectit:

  privacy:
    obfuscation:
      patterns:
        - pattern: toObfuscate
        - pattern: toObfuscateValue
          checkData: true

  instrumentation:

    scopes:
      TraceSettingsTest-root:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: root
            matcher-mode: STARTS_WITH
      TraceSettingsTest-nested:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: nestedC

      TraceSettingsTest-attributesSetterWithoutSpan:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: attributesSetterWithoutSpan
      TraceSettingsTest-attributesSetterWithoutSpanWithConditions:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: attributesSetterWithoutSpanWithConditions

      TraceSettingsTest-conditionalRoot:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: conditionalRoot

      TraceSettingsTest-named:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: named
            matcher-mode: STARTS_WITH

      TraceSettingsTest-asyncInterleaved:
        type:
          name: TraceSettingsTest$AsyncTask
          matcher-mode: ENDS_WITH
        methods:
          - name: doAsync

      TraceSettingsTest-samplingTestEndMarker:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: samplingTestEndMarker


      TraceSettingsTest-fixedSamplingRateTest:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: fixedSamplingRateTest

      TraceSettingsTest-dynamicSamplingRateTest:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: dynamicSamplingRateTest

      TraceSettingsTest-nestedSamplingTest:
        type:
          name: TraceSettingsTest
          matcher-mode: ENDS_WITH
        methods:
          - name: nestedSamplingTestRoot
          - name: nestedSamplingTestNested


    rules:
      TraceSettingsTest-startspan:
        scopes:
          TraceSettingsTest-root: true
          TraceSettingsTest-nested: true
        tracing:
          start-span: true

      TraceSettingsTest-attributesSetterWithoutSpan:
        scopes:
          TraceSettingsTest-attributesSetterWithoutSpan: true
        tracing:
          attributes:
            entry: entry_val
            exit: exit_val
            toObfuscate: exit_val
            anything: toObfuscate_val
        entry:
          entry_val:
            action: set
            constant-input: {value: "const"}
          toObfuscate_val:
            action: set
            constant-input: {value: "toObfuscateValue"}
        exit:
          exit_val:
            action: set
            data-input: {value: _returnValue}


      TraceSettingsTest-attributesSetterWithoutSpanWithConditions:
        scopes:
          TraceSettingsTest-attributesSetterWithoutSpanWithConditions: true
        tracing:
          attributes:
            entry: entry_val
            exit: exit_val
          attribute-conditions:
            only-if-true: _arg0
        entry:
          entry_val:
            action: set
            constant-input: {value: "const"}
        exit:
          exit_val:
            action: set
            data-input: {value: _returnValue}

      TraceSettingsTest-conditionalRoot:
        scopes:
          TraceSettingsTest-conditionalRoot: true
        tracing:
          start-span: true
          start-span-conditions:
            only-if-true: _arg0

      TraceSettingsTest-named:
        scopes:
          TraceSettingsTest-named: true
        tracing:
          start-span: true
          name: _arg0

      TraceSettingsTest-asyncInterleaved:
        scopes:
          TraceSettingsTest-asyncInterleaved: true
        tracing:
          start-span: true
          continue-span: span_id
          end-span: true
          end-span-conditions: {only-if-true: _arg3}
          store-span: span_id
          attributes:
            "1": _arg0
            "2": _arg1
            "3": _arg2

        entry:
          span_id:
            action: read_attachment_on_this
            constant-input: {key: "span_obj"}
        exit:
          do_write_span_obj:
            action: replace_attachment_on_this
            constant-input: {key: "span_obj"}
            data-input: {value: span_id}


      TraceSettingsTest-samplingTestEndMarker:
        scopes:
          TraceSettingsTest-samplingTestEndMarker: true
        tracing:
          start-span: true
          name: _arg0


      TraceSettingsTest-fixedSamplingRateTest:
        scopes:
          TraceSettingsTest-fixedSamplingRateTest: true
        tracing:
          start-span: true
          name: _arg0
          sample-probability: 0.5


      TraceSettingsTest-dynamicSamplingRateTest:
        scopes:
          TraceSettingsTest-dynamicSamplingRateTest: true
        tracing:
          start-span: true
          name: _arg0
          sample-probability: _arg1

      TraceSettingsTest-nestedSamplingTest:
        scopes:
          TraceSettingsTest-nestedSamplingTest: true
        tracing:
          start-span: true
          sample-probability: _arg0