inspectit:
  instrumentation:
    data-providers:
      assign:
        input:
          val: Object
        value: val

      get_method_name:
        input:
          _methodName: String
        value: _methodName

