name: Test eum Server

on:
  push:
    branches-ignore:
      - master
    paths:
      - '.github/workflows/eumserver_test.yml'
      - 'inspectit-ocelot-config'
      - 'components/inspectit-ocelot-eum-server/**'
      - '!components/inspectit-ocelot-eum-server/README.md'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/eumserver_test.yml'
      - 'inspectit-ocelot-config'
      - 'components/inspectit-ocelot-eum-server/**'
      - '!components/inspectit-ocelot-eum-server/README.md'
jobs:
  test:
    name: ${{ matrix.dockerimage }}
    runs-on: ubuntu-latest
    env:
      working-directory: ./components/inspectit-ocelot-eum-server
    strategy:
      fail-fast: false
      matrix:
        dockerimage:
          - 'openjdk:8-jdk'
          - 'openjdk:9-jdk'
          - 'openjdk:11-jdk'
          - 'ibmcom/ibmjava:8-sdk'
          - 'sgrio/java:jdk_8_ubuntu'
          - 'sgrio/java:jdk_11_ubuntu'
          - 'adoptopenjdk/openjdk8:latest'
    container: ${{ matrix.dockerimage }}
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: assemble
        run: ../../gradlew assemble
        working-directory: ${{env.working-directory}}
      - name: test
        run: ../../gradlew test
        working-directory: ${{env.working-directory}}